version: "3.7"

services:
  backend:
    container_name: mdwiki-backend
    build: ./backend
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

  frontend:
    container_name: mdwiki-frontend
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
